# Generated by Django 5.1.5 on 2026-04-19 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Expirada')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
