# Generated by Django 5.1.5 on 2026-04-19 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('billing_type', models.CharField(choices=[('HOURLY', 'Por hora'), ('FIXED', 'Precio fijo')], default='HOURLY', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20)),
                ('pipeline_stage', models.CharField(choices=[('LEAD', 'Lead'), ('PROPOSAL', 'Propuesta'), ('NEGOTIATION', 'Negociación'), ('ACTIVE', 'Activo'), ('COMPLETED', 'Completado'), ('BILLED', 'Facturado')], default='LEAD', max_length=20)),
                ('column_order', models.IntegerField(default=0)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('REFERRAL', 'Referido'), ('LINKEDIN', 'LinkedIn'), ('WEBSITE', 'Sitio web'), ('COLD_OUTREACH', 'Contacto frío'), ('OTHER', 'Otro')], max_length=20)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
