# Generated by Django 5.1.5 on 2026-04-19 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('NOTE_ADDED', 'Nota agregada'), ('INVOICE_SENT', 'Factura enviada'), ('INVOICE_PAID', 'Factura pagada'), ('TASK_DONE', 'Tarea completada'), ('STAGE_CHANGED', 'Etapa cambiada'), ('TIMER_ENTRY', 'Entrada de tiempo'), ('PROPOSAL_SENT', 'Propuesta enviada'), ('PROPOSAL_ACCEPTED', 'Propuesta aceptada'), ('CLIENT_CREATED', 'Cliente creado'), ('PROJECT_CREATED', 'Proyecto creado')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'freelancer')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='clients.tag'),
        ),
    ]
